[platformio]
default_envs = esp01_1m

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 74880
upload_speed = 115200

lib_deps =
  tzapu/WiFiManager @ ^2.0.17
  bblanchon/ArduinoJson @ ^6.21.5
  4-20ma/ModbusMaster @ ^2.0.1
  me-no-dev/ESP Async WebServer @ ^1.2.3
  me-no-dev/ESPAsyncTCP @ ^1.2.2

build_flags =
  -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
  -D NDEBUG
